##
# Ansible playbook for setting up a DevOps Enviroment.
#
- hosts: localhost
  become: yes
  vars:
     username: "{{ lookup('file', '/opt/Ansible/username.txt') }}"
  roles:
    - common
    - tools
    - database
    - devTools
    - devOps
