##
# Ansible playbook for setting up a DevOps Enviroment.
#
- hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - common
    - tools
    - database
    - devTools
    - devOps
