##
# Ansible playbook that uses the PostgreSQL module.
#
- hosts: localhost
  become: yes
  vars_prompt:
    - name: 'accepted_oracle_license'
      prompt: 'Do you accept the Java 8 Oracle License?'
      default: 'no'
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/java8.yml
      when: accepted_oracle_license == 'y' or accepted_oracle_license == 'yes' and (ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'xenial')
    - include: tasks/postgresql.yml
    - include: tasks/pgadmin.yml
