##
# Ansible playbook for setting up a Development Enviroment.
#
- hosts: localhost
  become: yes
  vars:
     username: "{{ lookup('file', '/opt/Ansible/username.txt') }}"
  roles:
    - common
    - tools
