##
# Ansible playbook for setting up a Tester Enviroment.
#
- hosts: localhost
  become: yes
  vars:
     username: "{{ lookup('file', '/tmp/Ansible/username.txt') }}"
  roles:
    - common
    - tools
    - database
    - devTools
